version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: authfox
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@test.lcl
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - 80:80
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

    
