name: docker testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check-out code
        uses: actions/checkout@v3

      - name: build docker
        run: docker build . -t test --pull --no-cache
